export const FETCH_CITIES_START = 'START_FETCHING_CITIES';
export type FETCH_CITIES_START = typeof FETCH_CITIES_START;

export const FETCH_CITIES_SUCCEEDED = 'FETCH_CITIES_SUCCEEDED';
export type FETCH_CITIES_SUCCEEDED = typeof FETCH_CITIES_SUCCEEDED;

export const FETCH_CITIES_FAILED = 'FETCH_CITIES_FAILED';
export type FETCH_CITIES_FAILED = typeof FETCH_CITIES_FAILED;